### ISSUE TITLE
Python environment error in `code-gen`

### ISSUE THREAD

**Issue by zonca** [Michael-D-Johnson/servicex-yt-deployment#1]
thanks @Michael-D-Johnson for sharing this recipe, I am trying to deploy this in KinD instead of minikube.

I get an error in the `code-gen` pod:

    [2022-03-22 16:02:35 +0000] [12] [ERROR] Exception in worker process    
    ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/__init__.py)                  
  
Full log: https://gist.github.com/37c77faf1d3073b9e0438987ac342978

Would you have any suggestions on what could be wrong?

**Comment by Michael-D-Johnson** [comment]
Ah yes. I've seen this issue. This is a problem with Flask 1.1.2 or 1.1.4. If you upgrade your Flask version in requirements.txt, that should remove this issue.

**Comment by zonca** [comment]
I don't see any `requirements.txt` in the repo, what are you referring to? I wouldn't want to build my own docker images. I would just like to test what you have.

**Comment by Michael-D-Johnson** [comment]
I committed a change to the repo that uses a different branch of the code_gen that has updated flask packages. This should avoid the "itsdangerous" errors. Let me know if you still encounter problems.

**Comment by zonca** [comment]
thanks for the fix,
all pods are running now,

```
python post.py 5000 yt.item.json 
Handling connection for 5000
{'request_id': '344a2345-bc9f-497f-b870-51949feca4ec'}
```

and if I check in the logs of the DID finder I see a file path:

    INFO servicex girder_did_finder None Metric: {"timestamp": "2022-03-29T18:49:21.874240", "file_path": "https://girder.hub.yt/api/v1/item/579fb0aa7b6f0800011ea3b6/download", "adler32": 0, "file_size": 0, "file_events": 0}
